CREATE SCHEMA IF NOT EXISTS pharmacy;

CREATE TABLE IF NOT EXISTS pharmacy.categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(80) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS pharmacy.materials (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    category_id integer NOT NULL REFERENCES pharmacy.categories(id),
    unit varchar(30) NOT NULL,
    image_url text NOT NULL,
    UNIQUE (name, category_id)
);

CREATE TABLE IF NOT EXISTS pharmacy.locations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS pharmacy.inventory_lots (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id integer NOT NULL REFERENCES pharmacy.materials(id),
    location_id integer NOT NULL REFERENCES pharmacy.locations(id),
    lot_number varchar(50) NOT NULL UNIQUE,
    quantity integer NOT NULL CHECK (quantity >= 0),
    status varchar(30) NOT NULL CHECK (status IN ('In stock', 'Low stock', 'Reorder')),
    expiry_date date NOT NULL
);

CREATE TABLE IF NOT EXISTS pharmacy.studies (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol_code varchar(40) NOT NULL UNIQUE,
    name varchar(160) NOT NULL,
    status varchar(30) NOT NULL CHECK (status IN ('Planning', 'Active', 'Closed')),
    start_date date NOT NULL,
    end_date date,
    CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS pharmacy.study_materials (
    study_id integer NOT NULL REFERENCES pharmacy.studies(id) ON DELETE CASCADE,
    material_id integer NOT NULL REFERENCES pharmacy.materials(id),
    required_quantity integer NOT NULL CHECK (required_quantity > 0),
    PRIMARY KEY (study_id, material_id)
);

INSERT INTO pharmacy.categories (name) VALUES
    ('Investigational drug'),
    ('Comparator'),
    ('Ancillary supply')
ON CONFLICT (name) DO NOTHING;

INSERT INTO pharmacy.locations (name) VALUES
    ('Pharmacy A · Cold storage'),
    ('Pharmacy A · Secure vault'),
    ('Depot B · Ambient'),
    ('Clinic 04 · Supply room')
ON CONFLICT (name) DO NOTHING;

INSERT INTO pharmacy.materials (name, category_id, unit, image_url)
SELECT seed.name, categories.id, seed.unit, seed.image_url
FROM (VALUES
    ('Caldovir 50 mg tablets', 'Investigational drug', 'kits', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80'),
    ('Caldovir 100 mg tablets', 'Investigational drug', 'kits', 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=900&q=80'),
    ('Placebo tablets', 'Comparator', 'kits', 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=900&q=80'),
    ('Comparator capsules', 'Comparator', 'bottles', 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=900&q=80'),
    ('Sterile dosing syringes', 'Ancillary supply', 'units', 'https://images.unsplash.com/photo-1576671081837-49000212a370?auto=format&fit=crop&w=900&q=80'),
    ('Temperature data loggers', 'Ancillary supply', 'units', 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=80')
) AS seed(name, category_name, unit, image_url)
JOIN pharmacy.categories AS categories ON categories.name = seed.category_name
ON CONFLICT (name, category_id) DO NOTHING;

INSERT INTO pharmacy.inventory_lots (material_id, location_id, lot_number, quantity, status, expiry_date)
SELECT materials.id, locations.id, seed.lot_number, seed.quantity, seed.status, seed.expiry_date
FROM (VALUES
    ('Caldovir 50 mg tablets', 'Pharmacy A · Cold storage', 'CDV50-24018', 1240, 'In stock', DATE '2027-04-30'),
    ('Caldovir 100 mg tablets', 'Pharmacy A · Secure vault', 'CDV100-24009', 186, 'Low stock', DATE '2027-01-31'),
    ('Placebo tablets', 'Pharmacy A · Cold storage', 'PCB-24021', 980, 'In stock', DATE '2027-05-31'),
    ('Comparator capsules', 'Depot B · Ambient', 'CMP-23114', 42, 'Reorder', DATE '2026-10-31'),
    ('Sterile dosing syringes', 'Clinic 04 · Supply room', 'SDS-24032', 3200, 'In stock', DATE '2029-12-31'),
    ('Temperature data loggers', 'Depot B · Ambient', 'TDL-24007', 74, 'Low stock', DATE '2030-06-30')
) AS seed(material_name, location_name, lot_number, quantity, status, expiry_date)
JOIN pharmacy.materials AS materials ON materials.name = seed.material_name
JOIN pharmacy.locations AS locations ON locations.name = seed.location_name
ON CONFLICT (lot_number) DO NOTHING;

INSERT INTO pharmacy.studies (protocol_code, name, status, start_date, end_date) VALUES
    ('CDV-301', 'Caldovir Phase III Efficacy Study', 'Active', DATE '2025-03-10', NULL),
    ('CDV-204', 'Caldovir Dose Optimization Study', 'Active', DATE '2025-06-02', NULL),
    ('CDV-109', 'Caldovir Tolerability Follow-up', 'Planning', DATE '2026-09-15', NULL)
ON CONFLICT (protocol_code) DO NOTHING;

INSERT INTO pharmacy.study_materials (study_id, material_id, required_quantity)
SELECT studies.id, materials.id, seed.required_quantity
FROM (VALUES
    ('CDV-301', 'Caldovir 50 mg tablets', 600),
    ('CDV-301', 'Placebo tablets', 450),
    ('CDV-204', 'Caldovir 100 mg tablets', 140),
    ('CDV-204', 'Comparator capsules', 60),
    ('CDV-109', 'Sterile dosing syringes', 500),
    ('CDV-109', 'Temperature data loggers', 25)
) AS seed(protocol_code, material_name, required_quantity)
JOIN pharmacy.studies AS studies ON studies.protocol_code = seed.protocol_code
JOIN pharmacy.materials AS materials ON materials.name = seed.material_name
ON CONFLICT (study_id, material_id) DO NOTHING;
