apiVersion: v1
kind: Service
metadata:
  name: argocd-demo-app-service
spec:
  type: NodePort
  selector:
    app: argocd-demo-app
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 31000 # Optional: Kubernetes will choose a port if this is omitted