apiVersion: v1
kind: Service
metadata:
  name: mcpserver
  labels:
    app: mcpserver
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: mcpserver