apiVersion: v1
kind: Pod
metadata:
  name: sample-workload-identity
  namespace: default
  labels:
    azure.workload.identity/use: "true"  # Required. Only pods with this label can use workload identity.
spec:
  serviceAccountName: $env:SERVICE_ACCOUNT_NAME
  containers:
    - image: busybox
      name: busybox
      command: ["sh", "-c", "sleep 3600"]