apiVersion: v1
kind: Secret
metadata:
 name: rg-dev-app-aso-credentials
 namespace: rg-dev-app
stringData:
 AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
 AZURE_TENANT_ID: ${AZURE_TENANT_ID}
 AZURE_CLIENT_ID: ${USER_ASSIGNED_IDENTITY_CLIENT_ID}
 USE_WORKLOAD_IDENTITY_AUTH: "true"