apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dynamo.yaml
- dynamo-pvc.yaml
- kaito.yaml
- kaito-podmonitor.yaml
- kuberay.yaml
- kuberay-podmonitor.yaml
- llmd.yaml
- llmd-podmonitor.yaml

